### ISSUE TITLE
Introduce a minimum cycle period

### ISSUE THREAD

**Issue by gyozosz** [agoraxyz/gold-rust#27]
## Description

Since the interactions with the blockchain have some limitations, the cycle period of all auctions could be above some minimal duration, that do not limit the use cases. Setting a minimum cycle period of 1 minute sounds reasonable.

The automatic freeze of idle auctions should be reevaluated so that it includes logic to rapid auctions with low cycle_periods. Beside the one-week inactivity a new condition would be useful on the number of idle cycles. After 50 idle cycles it seems reasonable to assume that the auction is safe to freeze.

**Comment by PopcornPaws** [comment]
Include some sanity checks for user input on the contract side as well:
- [ ] disallow `Some(0)` for auction cycle numbers in the contract
- [ ] ensure a 1 minute minimum to the cycle period
- [ ] disallow 0 token per cycle amount
- [ ] check auction start timestamp
- [ ] master edition NFT must be mutable
