### ISSUE TITLE
optionally use an already existing token mint for token auctions

### ISSUE THREAD

**Issue by PopcornPaws** [agoraxyz/gold-rust#53]
## Description
When creating a token-based auction, users should be able to provide an existing token mint account for per-cycle token minting. This raises a few issues that should be thought through.
- [x] mint and token accounts should be provided externally for every instruction call (because we cannot compute them as PDAs) -> this is not very convenient, but adds more flexibility
- [x] mint pubkey is saved to the auction state (same as now)
- [x] we always read this state to check whether the provided mint is the same
- [x] upon auction initialization, the mint should be an `Option<Pubkey>` and if it's `None` we create a new mint.

**Comment by gyozosz** [comment]
Resolved by #56
